require:
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'db/seeds/data.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/seeds/data.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*